language: cpp
matrix:
    include:
        - os: linux
          dist: bionic
          compiler: clang++
          env:
              - BOOST_VERSION=1.72.0
              - MATRIX_EVAL="CC=clang CXX=clang++"
              - TOOLSET=clang
              - CMAKE_OPTS="-DCODE_COVERAGE=OFF -DBUILD_DOC=OFF"
              - LFLAGS="-stdlib=libc++"
              - CXXFLAGS="-stdlib=libc++ -std=c++17"
          before_install:
              - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
              - sudo apt-get -q update
              - sudo apt-get install clang-8 libc++1-8 libc++abi1-8 libc++-8-dev
              - sudo ldconfig
        - os: linux
          dist: bionic
          compiler: gcc
          env:
              - BOOST_VERSION=1.72.0
              - MATRIX_EVAL="CC=gcc CXX=g++"
              - TOOLSET=gcc
              - CMAKE_OPTS="-DUSE_LLVM=OFF -DCODE_COVERAGE=OFF -DBUILD_DOC=OFF"
              - LFLAGS="-stdlib=libstdc++"
              - CXXFLAGS="-stdlib=libstdc++ -std=c++17"
          before_install:
              - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
              - sudo apt-get -q update
              - sudo apt-get install g++-9
              - sudo ldconfig
install:
  - eval "${MATRIX_EVAL}"
  ############################################################################
  # All the dependencies are installed in ${HOME}/deps/
  ############################################################################
  - DEPS_DIR="${HOME}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  ############################################################################
  # Install Boost headers
  ############################################################################
  - |
    BOOST_SRC_DIR=${DEPS_DIR}/boost-${BOOST_VERSION}-source
    BOOST_DIR=${DEPS_DIR}/boost-${BOOST_VERSION}
    if [[ "${BOOST_VERSION}" != "" ]]; then
      if [[ "${BOOST_VERSION}" == "trunk" ]]; then
        BOOST_URL="http://github.com/boostorg/boost.git"
        travis_retry git clone --depth 1 --recursive ${BOOST_URL} ${BOOST_SRC_DIR} || exit 1
        (cd ${BOOST_SRC_DIR} && ./bootstrap.sh && ./b2 headers) || exit 1
      else
        BOOST_URL="https://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION//\./_}.tar.gz"
        mkdir -p ${BOOST_SRC_DIR}
        { travis_retry wget -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${BOOST_SRC_DIR}; } || exit 1
      fi
      CMAKE_OPTIONS+=" -DBOOST_ROOT=${BOOST_DIR}"
    fi
  - (cd ${BOOST_SRC_DIR}/tools/build && ./bootstrap.sh --with-toolset=${TOOLSET} && ./b2 toolset=${TOOLSET} install --prefix=${DEPS_DIR}/b2)
  - export PATH=${DEPS_DIR}/b2/bin:${PATH}
  - b2 --version || true # b2 --version returns 1
  - cd ${BOOST_SRC_DIR}
  - b2 toolset=${TOOLSET} link=static cxxflags=${CXXFLAGS} linkflags=${LFLAGS} -j 4 --with-system --with-filesystem --with-log --with-thread --prefix=${BOOST_DIR} install

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi
  - cmake --version
before_script:
    - ${CXX} -v
script:
    - cd ${TRAVIS_BUILD_DIR}
    - mkdir build && cd build
    - cmake -DBOOST_ROOT=${BOOST_DIR} ../
    - make
    - cd ${TRAVIS_BUILD_DIR}/build/test
    - ./all_server_tests
