language: cpp
matrix:
  include:
    - os: linux
      dist: bionic
      compiler: clang
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - llvm-10
            - clang-10
            - libc++1-10
            - libc++-10-dev
            - libc++abi-10-dev
            - libunwind-dev
            - liblzma-dev
      env:
        - BOOST_VERSION=1.72.0
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"
        - TOOLSET=clang
        - CMAKE_OPTS="-DCODE_COVERAGE=ON -DBUILD_DOC=OFF"
        - LFLAGS="-stdlib=libc++ -lc++abi"
        - CXXFLAGS="-stdlib=libc++ -std=c++17"
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - BOOST_VERSION=1.72.0
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        - TOOLSET=gcc
        - CMAKE_OPTS="-DCODE_COVERAGE=OFF -DBUILD_DOC=OFF"
        - LFLAGS=" "
        - CXXFLAGS="-std=c++17"
before_install:
  - eval "${MATRIX_EVAL}"
install:
  ############################################################################
  # Create toolset-specific bin directory with symlinks to desired version
  # of toolset executables. This is to avoid using executables of older
  # toolset versions.
  ############################################################################
  - export TOOLSET_BIN="${TRAVIS_BUILD_DIR}/toolset-bin"
  - mkdir "$TOOLSET_BIN"
  - |
    if [[ "$TOOLSET" == "gcc" ]]; then
      ln -s /usr/bin/gcc-9 "${TOOLSET_BIN}/gcc"
      ln -s /usr/bin/g++-9 "${TOOLSET_BIN}/g++"
    fi
  - |
    if [[ "$TOOLSET" == "clang" ]]; then
      ln -s /usr/lib/llvm-10/bin/clang "${TOOLSET_BIN}/clang"
      ln -s /usr/lib/llvm-10/bin/clang++ "${TOOLSET_BIN}/clang++"
      ln -s /usr/lib/llvm-10/bin/llvm-cov "${TOOLSET_BIN}/llvm-cov"
      ln -s /usr/lib/llvm-10/bin/llvm-profdata "${TOOLSET_BIN}/llvm-profdata"
    fi
  # prepend the toolset bin directory to PATH so that it takes priority.
  - export PATH="${TOOLSET_BIN}:$PATH"

  ############################################################################
  # All the dependencies are installed in ${HOME}/deps/
  ############################################################################
  - DEPS_DIR="${HOME}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  ############################################################################
  # Compile and install Boost libraries
  ############################################################################
  - |
    BOOST_SRC_DIR=${DEPS_DIR}/boost-${BOOST_VERSION}-source
    BOOST_DIR=${DEPS_DIR}/boost-${BOOST_VERSION}
    if [[ "${BOOST_VERSION}" != "" ]]; then
      if [[ "${BOOST_VERSION}" == "trunk" ]]; then
        BOOST_URL="http://github.com/boostorg/boost.git"
        travis_retry git clone --depth 1 --recursive ${BOOST_URL} ${BOOST_SRC_DIR} || exit 1
        (cd ${BOOST_SRC_DIR} && ./bootstrap.sh && ./b2 headers) || exit 1
      else
        BOOST_URL="https://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION//\./_}.tar.gz"
        mkdir -p ${BOOST_SRC_DIR}
        { travis_retry wget -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${BOOST_SRC_DIR}; } || exit 1
      fi
      CMAKE_OPTIONS+=" -DBOOST_ROOT=${BOOST_DIR}"
    fi
  - cd ${BOOST_SRC_DIR}/tools/build
  - ./bootstrap.sh --with-toolset=${TOOLSET} || (cat bootstrap.log && exit 1)
  - ./b2 toolset=${TOOLSET} install --prefix=${DEPS_DIR}/b2
  - export PATH=${DEPS_DIR}/b2/bin:${PATH}
  - b2 --version || true # b2 --version returns 1
  - cd ${BOOST_SRC_DIR}
  - b2 toolset=${TOOLSET} link=static cxxflags="${CXXFLAGS}" linkflags="${LFLAGS}" -j 4 --with-system --with-filesystem --with-log --with-thread --prefix=${BOOST_DIR} install

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi
  - cmake --version
before_script:
  # Used as debugging information so we know what specific version is "visible"
  - |
    if [[ "$TOOLSET" == "clang" ]]; then
      clang --version
      llvm-profdata merge --version
    elif [[ "$TOOLSET" == "gcc" ]]; then
      g++ --version
    fi
script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake ${CMAKE_OPTS} -DBOOST_ROOT=${BOOST_DIR} ../
  - make
  - ./test/unit_tests
after_success:
  - |
    if [[ "$TOOLSET" == "clang" ]]; then
      cd ${TRAVIS_BUILD_DIR}/build
      make cov-lcov
      bash <(curl -s https://codecov.io/bash) -f ccov/all_tests.lcov || echo "Codecov did not collect coverage report"
    fi
