language: cpp
os: linux
dist: disco
addons:
    apt:
        packages:
            - clang-7
            - libboost-all-dev
            - cmake-data
            - cmake
            - libc++
            - libc++-dev
script:
    - clang++ -v
    - mkdir build && cd build
    - cmake ../
    - make
